#ifndef CODIGOS_ERROR_H
#define CODIGOS_ERROR_H

#define SIN_ERROR 0
#define ERROR_PUNTERO_NULO -1
#define ERROR_CAPACIDAD -2
#define ERROR_SIN_TERMINADOR -3
#define ERROR_MEMORIA -4
#define ERROR_SIN_CARACTER_VALIDO -5
#define ERROR_AL_ABRIR_ARCHIVO -6
#define ERROR_AL_CREAR_MATRIZ -7
#define ERROR_PARSEO -8
#define ERROR_PARAM_INVALIDOS -9


#endif