schema: "classroom50/repo-config/v1"
classroom: "p1-2026"
assignment: "tp2"
owner:
  username: "anon_013"
  id: 293134631
  accepted_at: "2026-09-09T20:13:43Z"
source:
  owner: "INGCOM-UNRN-P1"
  owner_id: 86799701
  repo: "TP2-2026"
  branch: "main"
