schema: "classroom50/repo-config/v1"
classroom: "p1-2026"
assignment: "tp1"
owner:
  username: "anon_017"
  id: 143362771
  accepted_at: "2026-09-08T22:10:49Z"
source:
  owner: "INGCOM-UNRN-P1"
  owner_id: 86799701
  repo: "TP1-2026"
  branch: "main"
