schema: "classroom50/repo-config/v1"
classroom: "p1-2026"
assignment: "tp4"
owner:
  username: "anon_014"
  id: 210442854
  accepted_at: "2026-09-22T22:59:15Z"
source:
  owner: "INGCOM-UNRN-P1"
  owner_id: 86799701
  repo: "TP4-2026"
  branch: "main"
