schema: "classroom50/repo-config/v1"
classroom: "p1-2026"
assignment: "tp4"
owner:
  username: "anon_002"
  id: 197310589
  accepted_at: "2026-09-23T00:19:19Z"
source:
  owner: "INGCOM-UNRN-P1"
  owner_id: 86799701
  repo: "TP4-2026"
  branch: "main"
