schema: "classroom50/repo-config/v1"
classroom: "p1-2026"
assignment: "tp1"
owner:
  username: "anon_008"
  id: 73611824
  accepted_at: "2026-09-06T14:05:15Z"
source:
  owner: "INGCOM-UNRN-P1"
  owner_id: 86799701
  repo: "TP1-2026"
  branch: "main"
