schema: "classroom50/repo-config/v1"
classroom: "p1-2026"
assignment: "tp2"
owner:
  username: "anon_012"
  id: 105023603
  accepted_at: "2026-09-16T12:57:32Z"
source:
  owner: "INGCOM-UNRN-P1"
  owner_id: 86799701
  repo: "TP2-2026"
  branch: "main"
