schema: "classroom50/repo-config/v1"
classroom: "p1-2026"
assignment: "tp2"
owner:
  username: "anon_006"
  id: 93556056
  accepted_at: "2026-09-17T00:29:54Z"
source:
  owner: "INGCOM-UNRN-P1"
  owner_id: 86799701
  repo: "TP2-2026"
  branch: "main"
