schema: "classroom50/repo-config/v1"
classroom: "p1-2026"
assignment: "tp1"
owner:
  username: "anon_004"
  id: 225635401
  accepted_at: "2026-09-04T21:12:30Z"
source:
  owner: "INGCOM-UNRN-P1"
  owner_id: 86799701
  repo: "TP1-2026"
  branch: "main"
