schema: "classroom50/repo-config/v1"
classroom: "p1-2026"
assignment: "tp1"
owner:
  username: "anon_023"
  id: 225020686
  accepted_at: "2026-09-05T00:22:26Z"
source:
  owner: "INGCOM-UNRN-P1"
  owner_id: 86799701
  repo: "TP1-2026"
  branch: "main"
